version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/test"
    schedule:
      interval: "weekly"
    groups:
      go_modules:
        patterns:
          - "*"
