name: Scheduled Terraform Test

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  terratest:
    name: Run Terratest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 0.13.1

      - name: Download Go Modules
        working-directory: test
        run: go mod download

      - name: Run Terratest
        working-directory: test
        run: go test -v

  terraform-compliance:
    name: Run Terraform Compliance
    runs-on: ubuntu-latest
    needs: terratest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 0.13.1

      - name: Terraform Init
        run: terraform init -backend=false
        working-directory: ./example

      - name: Terraform Plan
        run: terraform plan -out=tfplan -input=false
        working-directory: ./example

      - name: Install terraform-compliance
        run: |
          pip install terraform-compliance

      - name: Run terraform-compliance
        run: terraform-compliance -p ./example/tfplan -f ./compliance/features
